## In multiple variable regression, X has to be 2D. Dataframes are already 2D. Rest have to converted into 2D by [[]] or reshape.(-1,1).

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

%matplotlib inline

In [20]:
df = pd.read_csv("8.1 1.02. Multiple linear regression.csv")

In [21]:
df.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [22]:
## let's build multivariable regression model

In [24]:
x = df[["Rand 1,2,3", "SAT"]]
## remember the order

In [26]:
y = df["GPA"]

In [27]:
reg = LinearRegression()

In [95]:
reg.fit(x,y)

LinearRegression()

In [99]:
reg.predict([[3,1700]])

array([3.08224421])

## R square value

In [100]:
reg.score(x,y)

0.4066811952814282

In [101]:
## increasing variable increasing R2 value but decreases Adj. R2 value

In [102]:
## Adj. R2 value shows how model is actual behaving

In [103]:
## have to remove unimportant variable usinf f regression

## F regression helps to find out p values by doing regresiion with individual variable

In [104]:
## import 

In [105]:
from sklearn.feature_selection import f_regression

In [106]:
f_reg = f_regression(x,y)
f_reg

(array([ 0.17558437, 56.04804786]), array([6.76291372e-01, 7.19951844e-11]))

In [107]:
## second one os p value of variables in defined order

In [108]:
p_values = f_reg[1]
p_values

array([6.76291372e-01, 7.19951844e-11])

In [109]:
## just round it by 3 decimals

In [110]:
p_values.round(3)

array([0.676, 0.   ])

In [111]:
## Rand 1,2,3 has p value == 0.676
## sat has p value == 0

In [112]:
## we can drop Rand 1,2,3

In [113]:
## IMPORTANT ##
     ## this p value just gives values from simple individual regression
    ## not from multi variable

## creat summary table

In [114]:
summary = pd.DataFrame(data = x.columns.values, columns = ["Features"])

##columns.values helps when we have more than 100 features

In [115]:
summary

Features
0  Rand 1,2,3
1         SAT

In [116]:
## now add p values and Coefficients

In [117]:
summary["P values"] = p_values.round(3)

In [118]:
summary["Coefficient"] = reg.coef_

In [119]:
summary

Features  P values  Coefficient
0  Rand 1,2,3     0.676    -0.008270
1         SAT     0.000     0.001654

In [120]:
## p values just says which one to remove but the importance of others?

In [121]:
## having 2 variables p = 0 does not mean both equally important

## Standardization

In [122]:
## to make magnitude of all the features standard

In [123]:
from sklearn.preprocessing import StandardScaler

In [124]:
scaler = StandardScaler()

In [125]:
scaler.fit(x)
## this calculates mean and std for each feature

StandardScaler()

In [126]:
x_scaled = scaler.transform(x)

In [154]:
x_scaled

## converting X 2d into standard x_scaled 2d

array([[-1.24637147, -1.26338288],
       [ 1.10632974, -1.74458431],
       [ 1.10632974, -0.82067757],
       [ 1.10632974, -1.54247971],
       [-0.07002087, -1.46548748],
       [-1.24637147, -1.68684014],
       [-0.07002087, -0.78218146],
       [-1.24637147, -0.78218146],
       [-0.07002087, -0.51270866],
       [ 1.10632974,  0.04548499],
       [ 1.10632974, -1.06127829],
       [-0.07002087, -0.67631715],
       [-1.24637147, -1.06127829],
       [ 1.10632974, -1.28263094],
       [-0.07002087, -0.6955652 ],
       [-0.07002087,  0.25721362],
       [ 1.10632974, -0.86879772],
       [-0.07002087, -1.64834403],
       [ 1.10632974, -0.03150724],
       [ 1.10632974, -0.57045283],
       [ 1.10632974, -0.81105355],
       [ 1.10632974, -1.18639066],
       [ 1.10632974, -1.75420834],
       [-1.24637147, -1.52323165],
       [-1.24637147,  1.23886453],
       [-1.24637147, -0.18549169],
       [-1.24637147, -0.5608288 ],
       [ 1.10632974, -0.23361183],
       [-1.24637147,

In [155]:
## now fit the model

In [156]:
reg.fit(x_scaled, y)

LinearRegression()

In [157]:
new_summary = pd.DataFrame(data = ["Bias", "Rand 1,2,3", "SAT"], columns = ["Features"])

In [158]:
new_summary["Weights"] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [159]:
new_summary
## Intercept renamed as bias coz that's what people prefer, Weights means actuall weight in the result (Importance)
## -0.007 is almost zero, does not contribute

Features   Weights
0        Bias  3.330238
1  Rand 1,2,3 -0.007030
2         SAT  0.171814

## Prediction with standardize model

In [199]:
testing_data = pd.DataFrame({"Rand 1,2,3" : [1,2], "SAT" : [1800,2100]})
## taking random data to test model as we did not divide train and test data

In [193]:
reg.predict(testing_data)

array([312.58821497, 364.12535273])

In [194]:
## now This shows GPA wchich cannot be more that 4

In [195]:
## this is happening becoz this data also have to be standardize

In [196]:
new_testing_data = scaler.transform(testing_data)
new_testing_data

array([[-1.24637147, -0.43571643],
       [-0.07002087,  2.45149212]])

In [197]:
reg.predict(new_testing_data)

array([3.26413803, 3.75193075])

In [142]:
## now, this shows GPA

## Prediction without Rand 1,2,3

In [166]:
## we said -0.007 does not contribute anything, let test it

In [167]:
model = LinearRegression()

In [168]:
x_new = x_scaled[:,1].reshape(-1,1)
## still have standardize data but only for SAT means droppes rand 1,2,3

In [185]:
model.fit(x_new, y)

LinearRegression()

In [206]:
SAT_test = new_testing_data[:,1].reshape(-1,1)

In [208]:
model.predict(SAT_test)

array([3.25527879, 3.7519852 ])

In [209]:
## same result

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
car = pd.read_csv("carprices.csv")

In [3]:
car

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [4]:
car.rename(columns = {"Sell Price($)" : "Sell Price", "Age(yrs)" : "Age"}, inplace = True)
car

Car Model  Mileage  Sell Price  Age
0                  BMW X5    69000       18000    6
1                  BMW X5    35000       34000    3
2                  BMW X5    57000       26100    5
3                  BMW X5    22500       40000    2
4                  BMW X5    46000       31500    4
5                 Audi A5    59000       29400    5
6                 Audi A5    52000       32000    5
7                 Audi A5    72000       19300    6
8                 Audi A5    91000       12000    8
9   Mercedez Benz C class    67000       22000    6
10  Mercedez Benz C class    83000       20000    7
11  Mercedez Benz C class    79000       21000    7
12  Mercedez Benz C class    59000       33000    5

In [7]:
dummies = pd.get_dummies(car, drop_first = True)
## easy method to creat dummies

In [10]:
dummies.columns

Index(['Mileage', 'Sell Price', 'Age', 'Car Model_BMW X5',
       'Car Model_Mercedez Benz C class'],
      dtype='object')

In [11]:
dummies = dummies[['Sell Price', 'Mileage', 'Age', 'Car Model_BMW X5',
       'Car Model_Mercedez Benz C class']]


In [12]:
dummies

Sell Price  Mileage  Age  Car Model_BMW X5  \
0        18000    69000    6                 1   
1        34000    35000    3                 1   
2        26100    57000    5                 1   
3        40000    22500    2                 1   
4        31500    46000    4                 1   
5        29400    59000    5                 0   
6        32000    52000    5                 0   
7        19300    72000    6                 0   
8        12000    91000    8                 0   
9        22000    67000    6                 0   
10       20000    83000    7                 0   
11       21000    79000    7                 0   
12       33000    59000    5                 0   

    Car Model_Mercedez Benz C class  
0                                 0  
1                                 0  
2                                 0  
3                                 0  
4                                 0  
5                                 0  
6                                 0  
7                                 0  
8                                 0  
9                                 1  
10                                1  
11                                1  
12                                1

In [15]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
X = dummies[["Mileage", "Age","Car Model_BMW X5", "Car Model_Mercedez Benz C class"]]
vif = pd.DataFrame()

vif["VIF Factor"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif["features"] = X.columns

In [16]:
vif

VIF Factor                         features
0  919.805973                          Mileage
1  914.618437                              Age
2    1.493821                 Car Model_BMW X5
3    1.979932  Car Model_Mercedez Benz C class